"""rename department

Revision ID: 977ee0319701
Revises: 8ff2c955cd63
Create Date: 2024-05-30 08:57:50.214013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977ee0319701'
down_revision = '8ff2c955cd63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
